"""empty message

Revision ID: 4573602ae243
Revises: 
Create Date: 2018-08-03 15:25:53.857201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4573602ae243'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('next_phase', sa.Enum('sub_domain', 'root_domain', 'manager', 'need_verification', name='phaseenum'), nullable=True),
    sa.Column('next_mail_date', sa.Date(), nullable=True),
    sa.Column('first_attempt', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_index(op.f('ix_domain_domain'), 'domain', ['domain'], unique=True)
    op.create_index(op.f('ix_domain_email'), 'domain', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_email'), table_name='domain')
    op.drop_index(op.f('ix_domain_domain'), table_name='domain')
    op.drop_table('domain')
    # ### end Alembic commands ###
